### ISSUE TITLE
GetChildren error on deny of menu item in admin

### ISSUE THREAD

**Issue by nicholasmscott** [arckinteractive/Roles#4]
Hiya

I'm getting a problem with the latest version when trying to hide the 'settings' menu in admin

Fatal error: Call to a member function getChildren() on a non-object in /home/elgg/test-www/engine/lib/admin.php on line 390

The roles code is:
array('page::settings' => array('rule' => 'deny','context' => 'admin',))

I assume this is something to do with the recursive code, is there any fix I could quickly implement?

Cheers
Nick

**Comment by mrclay** [comment]
@nicholasmscott I'd consider this an Elgg core bug. If you're running 1.10 and it persists, please feel free to file it.
